version: '3'

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env
    ports:
      - "9000:9000"
      - "10070:50070"

  datanode:
    image: dlpgft/datanode:hadoop2.7.4-0.2
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - hadoop.env
    ports:
      - "10075:50075"


  
  zookeeper:
    image: debezium/zookeeper:1.5
    container_name: zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888


  kafka:
    image: debezium/kafka:1.5
    container_name: kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181


  mysql:
    image: debezium/example-mysql:1.5
    container_name: mysql
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw

  adminer:
    image: adminer
    container_name: mysql_ui
    restart: always
    ports:
      - 8090:8080

  connect:
    image: debezium/connect:1.5
    container_name: connect
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses


  jupyter:
    build: jupyter/
    container_name: jupyter
    ports: 
      - 8888:8888
    environment: 
      - JUPYTER_TOKEN=easy
      - GRANT_SUDO="yes"
    user:
      "root"



  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    ports:
      - 9047:9047


  superset:
    build: superset/
    container_name: superset
    ports: 
      - 8080:8080

volumes:
  hadoop_namenode:
  hadoop_datanode:







      






  

